bk-2before_debug-master/config/routes.rb
Rails.application.routes.draw do
root to: 'home#top'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
	  get '/home/about'
	  get '/users/:id/following' => 'users#follow', as:'follow'
	  get '/users/:id/followers' => 'users#follower', as:'follower'
  resources :books do
	  resource :favorites, only: [:create, :destroy]
	  resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bk-2before_debug-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bk-2before_debug-master/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

def already_favorited?(user)
  	self.favorites.exists?(user_id: user.id)
  end
end

bk-2before_debug-master/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bk-2before_debug-master/app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates_uniqueness_of :book_id, scope: :user_id
end

bk-2before_debug-master/app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'


	validates :user_id, presence: true
	validates :follow_id, presence: true
end

bk-2before_debug-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  attachment :profile_image
  # validates :name, presence: true 
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def already_favorited?(book)
  	self.favorites.exists?(book_id: book.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

bk-2before_debug-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session
  def after_sign_in_path_for(resource)
    book_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

bk-2before_debug-master/app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :eroos, only: [:edit,:update]
  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def destroy
    @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
  end

  def new
    @books = Book.new
    @user = current_user
    end

  def create
    @book  = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id),notice: "You have creatad book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @books = Book.all
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id),notice: "You have updated book successfully."
    else
      render :edit
     end
  end
  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @comment = Comment.new
    @comments = @book.comments

  end
  private
  # ストロングパラメータ
  def eroos
    book = Book.find(params[:id])
    user = current_user
    if user.id != (book.user_id).to_i
      redirect_to books_path
    end
 end

 def book_params
    params.require(:book).permit(:title, :body,:user_id)
  end
end

bk-2before_debug-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

def create
	@book = Book.find(params[:book_id])
	@comment = current_user.comments.new(comment_params)
	@comment.book_id = @book.id
	@comment.save
	redirect_to book_path(@book)
end

def destroy
	comment = current_user.comments.find(params[:id])
	comment.destroy

	redirect_to [:book, {id:params[:book_id]}]
end

private

def comment_params
	params.require(:comment).permit(:body)
	end
end

bk-2before_debug-master/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@favorite = current_user.favorites.create(book_id: params[:book_id])
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@book = Book.find(params[:book_id])
		@favorite = current_user.favorites.find_by(book_id:@book.id)
		@favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

bk-2before_debug-master/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

bk-2before_debug-master/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :set_user

	def create
		following = current_user.follow(@user)
		if following.save
			flash[:success] = 'ユーザーをフォローしました'

			redirect_to @user
		else
			flash.now[:alert] = 'ユーザーのフォローに失敗しました'

			redirect_to @user
		end
	end


	def destroy
		following = current_user.unfollow(@user)

		if following.destroy
			flash[:success] = 'ユーザーのフォローを解除しました'

			redirect_to @user
		else
			flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'

			redirect_to @user
		end
	end

	private
	def set_user
		@user = User.find(params[:follow_id])
	end


end

bk-2before_debug-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :eroos, only: [:edit,:update]
  def edit
    @user = User.find(params[:id])
  end
  def show
    @user = User.find(params[:id])
    @newBook = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
       @user = current_user
       @newBook = Book.new
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def follow
      @user  = User.find(params[:id])
      @users = @user.followings
  end

  def follower
    @user  = User.find(params[:id])
    @users = @user.followers
end

  private
  def eroos
    user = User.find(params[:id])
    if  (current_user.id !=  user.id)
      redirect_to user_path(current_user.id)
    end
end
  def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

bk-2before_debug-master/app/helpers/application_helper.rb
module ApplicationHelper
end

bk-2before_debug-master/app/helpers/books_helper.rb
module BooksHelper
end

bk-2before_debug-master/app/helpers/comments_helper.rb
module CommentsHelper
end

bk-2before_debug-master/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bk-2before_debug-master/app/helpers/home_helper.rb
module HomeHelper
end

bk-2before_debug-master/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bk-2before_debug-master/app/helpers/users_helper.rb
module UsersHelper
end

bk-2before_debug-master/app/views/books/_newform.html.erb
<h1>New book</h1>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

bk-2before_debug-master/app/views/books/edit.html.erb
<div class="container">

<% if @book.errors.any? %> 
  <%= @book.errors.count %>件のerrorが発生しました 
  <% @book.errors.full_messages.each do |message| %> 
  <%= message %> 
   <% end %> 
   <% end %> 

  <h1>Editing Book</h1>

  <%= form_for(@book) do |f| %>
 
  <h4>Title</h4>
  <%= f.text_field :title %>
 
  <h4>Opinion</h4>
  <%= f.text_area :body %>
 s
  <%= f.submit 'Update Book' %>

  <%= link_to 'Show',book_path %>
  <%= link_to 'Back',books_path %>
<% end %>

bk-2before_debug-master/app/views/books/index.html.erb
						<div class="container">
						  <% if @book.errors.any? %> 
							<%= @book.errors.count %>件のerrorが発生しました 
							<% @book.errors.full_messages.each do |message| %> 
							<%= message %> 
							 <% end %> 
							 <% end %> 


							<div class="row">
								<div class="col-xs-3">
									<%= render 'users/profile', user: @user %>
									<%= render 'books/newform', book: @book %>


								</div>
								<div class="col-xs-9">
									<h2>Books</h2>

						    <table class="table">
						  <thead>
						    <tr>
						      <th></th>
						      <th scope="col">Title</th>
						      <th scope="col">Opinion</th>
						      <th scope="col"> </th>
						    </tr>
						  </thead>
						  <tbody>
						    <% @books.each do |book| %>
						  <tr>
						  	<td><%= link_to user_path(book.user) do %>
						  		<%= attachment_image_tag book.user, :profile_image, size: "30x30",format: 'jpg', fallback: "no_image.jpg" %><% end %></td>
						    <td><%= link_to book.title,book_path(book.id) %></td>
						    <td><%= book.user.name %></td>
						    <td>
						    	<% if current_user.already_favorited?(book) %>
						    	　<%= link_to book_favorites_path(book.id), method: :delete do %>
						    　　	　　<i class="fas fa-heart"></i>
						    	　<% end %>
						    	<% else %>
						    	　<%= link_to book_favorites_path(book), method: :post do %>
						    		<i class="far fa-heart"></i>
						    	　<% end %>
						    	<% end %>
						    	<%= book.favorites.count %>
							</td>
							<td>コメント数：<%= book.comments.count %></td>
						　　</tr>
						  　<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>

bk-2before_debug-master/app/views/books/show.html.erb
<<div class="container">
<% if @book.errors.any? %> 
	<%= @book.errors.count %>件のerrorが発生しました 
	<% @book.errors.full_messages.each do |message| %> 
	<%= message %> 
	 <% end %> 
	 <% end %> 

<div class="container">
	<div class="row">
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %> 
		<div class="col-xs-3">
			<%= render 'users/profile', user: @book.user %>
			<%= render 'books/newform', book: @newbook %>
   

		</div>
		<div class="col-xs-9">
			<h2>Book detail</h2>

    <table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

  <tbody>
  <tr>
  	<td><%= attachment_image_tag @book.user, :profile_image, format: 'jpg',  size: "30x30", fallback: "no_image.jpg" %>
  		<br>
  		<%= link_to @book.user.name,user_path(@book.user.id) %>
    </td>
    <td><%= link_to @book.title,book_path %></td>
    <td><%= @book.body %></td>
    <td><% if @book.already_favorited?(current_user) %>
						    	　<%= link_to book_favorites_path(@book), method: :delete do %>
						    　　	　　<i class="fas fa-heart" ></i>
						    	　<% end %>
						    	<% else %>
						    	　<%= link_to book_favorites_path(@book), method: :post do %>
						    		<i class="far fa-heart" ></i>
						    	　<% end %>
						    	<% end %>
						    	<%= @book.favorites.count %>
	</td>
	<td>
  <i class="fa fa-comment"></i>
 <%= @book.comments.count %>
	</td>

    <td><% if @book.user == current_user %> <%= link_to "Edit",edit_book_path(@book.id) %><% end %></td>

    <td><% if @book.user == current_user %> <%= link_to "Destroy",book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %> <% end %></td>
  </tr>
				  	</tbody>
				</table>
		<% @comments.each do |comment| %>
		<%= attachment_image_tag comment.user, :profile_image, format: 'jpg',  size: "30x30", fallback: "no_image.jpg" %>
		<%= comment.user.name %>
		<%= comment.body%>
	<div>
		<%= link_to 'delete', [@book,comment], method: :delete %>
	</div>
		<% end %>
		<%= form_for [@book,@comment] do |f| %>
		<%= f.text_field :body %>
		<%= f.submit %>
		<% end %>
  			</div>
		</div>
	</div>
</div>

bk-2before_debug-master/app/views/home/about.html.erb
<div class="body">
	<div class="container">

		<p id="notice"></p>

<h1>welcome to<span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>  !!</h1>

</div>
</div>

<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-3 col-xs-offset-9">
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>



</body>

bk-2before_debug-master/app/views/home/top.html.erb
<div class="container">
<div class="row">
	<div class="top-message col-md-offset-3 col-md-5">
		<div class="text-field">
			<% if flash[:notice] %>
			<p><%= flash[:notice] %></p>
			<% end %>

			<p>
		<h3>welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers  !!<br></h3>
	</p>
	<p>
	<h3>
	In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</h3>
</p>
<p>
	<h5>
	you can share and exchange your opinions , inpressions , and emotions<br>
			about varioius books!</h5>
		</p>
	</div>

				<div class="row">
					<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
				</div>
				<div class="row">
					<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
				</div>
			</div>

	</div>
</div>

bk-2before_debug-master/app/views/layouts/application.html.erb
    <!DOCTYPE html>
<html>
  <head>

    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8adf4a6155.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <p class="navbar-text">Bookers</p>
        </div>
        <div class="collapse navbar-collapse" id="navbarEexample1">

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>

              <li>
                <%= link_to ' Home', book_path(current_user.id), class: "glyphicon glyphicon-home" %>
                </li>
              <li>
                <%= link_to ' Users', users_path, class: "glyphicon glyphicon-user" %>
                </li>
              <li>
                <%= link_to ' Books', books_path, class: "glyphicon glyphicon-book" %>
                </li>
              <li>
                <%= link_to ' logout', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>

                </li>
            <% else %>
              <li>
                <%= link_to ' Home', root_path, class: "glyphicon glyphicon-home" %>
                </li>
              <li>
                <%= link_to ' About', home_about_path, class: "glyphicon glyphicon-link" %>
                </li>
              <li>
                <%= link_to ' sign up', new_user_registration_path, class: "glyphicon glyphicon-edit" %>

                </li>
              <li>
                <%= link_to ' login', new_user_session_path, class: "glyphicon glyphicon-log-in" %>

                </li>
            <% end %>
          </ul>
       </div>
      </div>
    </nav>
      <p id="notice"><%= notice %></p>
      <%= yield %>

      </body>
    </html>

bk-2before_debug-master/app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

bk-2before_debug-master/app/views/users/_profile.html.erb
<h2>User info</h2>

 
<%= attachment_image_tag @user, :profile_image, size: "50x50",format: 'jpg', fallback: "no_image.jpg" %>
<table class="table">

<tbody>
	<tr></tr>
<tr>
	<th>name</th>
  <th><%= user.name %></th>
</tr>
<tr>
	<th>introduction</th>
	<th><%= user.introduction %></th>
</tr>
<tr>
	<td>follows:<%= link_to user.followings.count,follow_path(user) %></td>
</tr>
<tr>
	<td>followers:<%= link_to user.followers.count,follower_path(user) %></td>
</tr>
</tbody>
</table>

<div class="row">
	<% if user == current_user %>
  <%= link_to "Edit", edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_" %>
<% end %>
<%= render 'relationships/follow_button', user: user %>
</div>

bk-2before_debug-master/app/views/users/edit.html.erb
<section class="hero is-success">
	<div class="hero-body">
		<div class="container">
				<h1 class="titile">
				ユーザー編集
				</h1>
			</div>
		</div>
</section>
	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
			<%= @user.errors.count %>件errorが発生しました
				<% @user.errors.full_messages.each do |message| %>
				<%= message %>
				<% end %>
				<% end %>
	<!-- エラーメッセージ表示-->
			<h2>User info</h2>
			<section class="section">
				<div class="container">
					<div class="columns is-centered">
				<div class="column is-6">
				<%= form_for(@user) do |f| %>
				
				<h4>Title</h4>
				<%= f.text_field :name %>

				<h4>Opinion</h4>
				<%= f.text_field :introduction %>
				<%= f.attachment_field :profile_image %>
					<%= f.submit 'Update User' %>

					<% end %>
				</div>
			</div>

			<footer>
				<div class="container">
					<div class="row">
						<div class="col-xs-3 col-xs-offset-9">
							<p>CopyRight Infratop.inc</p>
						</div>
					</div>
				</div>
			</footer>
					
					</body

bk-2before_debug-master/app/views/users/follow.html.erb
<div style='margin-top: 70px'>
<div class="container">
  <div class="row">
  	<div class="col-xs-9">
      <h2>Follow User</h2>
		<% if @user.followings.blank? %>
		<p>フォローしてません。</p>
        <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @user.followings.each do |user| %>
	<tr>
    <td><%= user.name %></td>
    <td>フォロー数:<%= user.followings.count %></td>
    <td>フォロワー数:<%= user.followers.count %></td>
  <td><%= link_to "Show" ,user_path(user.id) %></td>
  <% end %>
     </table>
       <% end %>
  </div>
</div>
</div>

bk-2before_debug-master/app/views/users/follower.html.erb
<div style='margin-top: 70px'>
<div class="container">
  <div class="row">
  	<div class="col-xs-9">
      <h2>Follower User</h2>
      <% if @user.followers.blank? %>
		<p>フォローされてません。</p>
        <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @user.followers.each do |user| %>
	<tr>
    <td><%= user.name %></td>
    <td>フォロー数:<%= user.followings.count %></td>
    <td>フォロワー数:<%= user.followers.count %></td>
  <td><%= link_to "Show" ,user_path(user.id) %></td>
  <% end %>
     </table>
     <% end %>
  </div>
</div>
</div>

bk-2before_debug-master/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'users/profile', user: @user %>
      <%= render 'books/newform',book: @newBook%>

    </div>
    <div class="col-xs-9">
      <h2>Users</h2>

      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :size, 20, 20,format: 'jpg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
     <td>
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
              <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                <%= hidden_field_tag :follow_id, user.id %>
                <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
              <% end %>
            <% else %>
              <%= form_for(current_user.relationships.build) do |f| %>
                <%= hidden_field_tag :follow_id, user.id %>
                <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
              <% end %>
            <% end %>
          <% end %>
    </td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td><%= link_to "Show" ,user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

bk-2before_debug-master/app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
      
			<%= render 'users/profile', user: @user %>
			<%= render 'books/newform', book: @newBook %>
			
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
			<thead>
    <tr>
    	<th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
  <tr>
  	<td><%= attachment_image_tag @book, :profile_image, size: "30x30",format: 'jpg', fallback: "no_image.jpg" %></td>
    <td><%= link_to book.title,book_path(book.id) %></td>
    <td><%= book.body %></td>
    <% end %>
  </tbody>
</table>
		</div>
	</div>
</div>